
// GET REQUEST ----------> 
export const GET_PRODUCTFISHDATA_REQUEST = "GET_PRODUCTFISHDATA_REQUEST" ;
export const GET_PRODUCTFISHDATA_SUCCESS = "GET_PRODUCTFISHDATA_SUCCESS" ;
export const GET_PRODUCTFISHDATA_FAILURE = "GET_PRODUCTFISHDATA_FAILURE" ;

